name: Build and Test

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
    
    - name: Cache pub dependencies
      uses: actions/cache@v4
      with:
        path: ${{ env.PUB_CACHE }}
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
    
    - name: Download dependencies
      run: flutter pub get
    
    - name: Analyze project source
      run: flutter analyze
    
    - name: Run tests
      run: flutter test --coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
    
    - name: Build APK (fat)
      run: flutter build apk --release
    
    - name: Build APK (split per ABI)
      run: flutter build apk --release --split-per-abi
    
    - name: Build App Bundle
      run: flutter build appbundle --release
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-packages
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          build/app/outputs/flutter-apk/app-x86_64-release.apk
          build/app/outputs/bundle/release/app-release.aab

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          build/app/outputs/flutter-apk/app-x86_64-release.apk
          build/app/outputs/bundle/release/app-release.aab
        name: Release ${{ github.ref_name }}
        body: |
          Release ${{ github.ref_name }}
          
          This release includes:
          - Universal APK (app-release.apk)
          - Split APKs for different architectures:
            - ARM 32-bit (app-armeabi-v7a-release.apk)
            - ARM 64-bit (app-arm64-v8a-release.apk)
            - x86_64 (app-x86_64-release.apk)
          - Android App Bundle (app-release.aab)
          
          Changes in this version:
          - Please check the commit history for details
          
          Note: For most users, installing the appropriate split APK for their device architecture will result in a smaller app size.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 